name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.4"
      - name: Run tests
        run: go test -v
