name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.4"
      - name: Run tests
        env: # Or as an environment variable
          JSON_GOOGLE_CREDS_B64: ${{ secrets.JSON_GOOGLE_CREDS_B64 }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go test -v
